// Code generated by hero.
// source: E:\GOLANG\src\TopLearn\WebApp\template\login.html
// DO NOT EDIT!
package gotemplate

import (
	"io"

	"github.com/shiyanhui/hero"
)

func LoginHandler(msg []string, w io.Writer) {
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`<!DOCTYPE html>

<html lang="fa">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>بلاگ</title>
    <link rel="stylesheet" href="/Static/assets/dist/css/bootstrap.min.1.css" />
    <link rel="stylesheet" href="/Static/css/customCss.css" />
    `)
	_buffer.WriteString(`
</head>

<body>
    <div class="div-mainMenu"></div>
    <div class="container">

        <div class="row mt-4">
            `)
	_buffer.WriteString(`
    <div class="col-12">
        <div class="card mb-4 ">
            <div class="card-body text-primary">
                <section>
                    <form action="/Login" method="post">
                        <h4>ورود به سایت</h4>
                        <hr />
                        `)
	if msg != nil {
		_buffer.WriteString(`
                        <div class="row">
                            <div class="col-12">
                                `)
		for _, m := range msg {
			_buffer.WriteString(`
                                    <p class="text-danger">
                                            `)
			hero.EscapeHTML(m, _buffer)
			_buffer.WriteString(`
                                    </p>
                                `)
		}
		_buffer.WriteString(`
                            </div>
                        </div>
                        `)
	}
	_buffer.WriteString(`
                        <div class="form-group">
                            <label>ایمیل</label>
                            <input name="email"  class="form-control" />
                        </div>
                        <div class="form-group">
                            <label>کلمه عبور</label>
                            <input name="password"  class="form-control" />
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">ورود</button>
                        </div>
                        <div class="form-group">
                            <p>
                                <a href="/">فراموشی کلمه عبور</a>
                            </p>
                            <p>
                                <a href="/">ثبت نام</a>
                            </p>
                        </div>
                    </form>
                </section>
            </div>
        </div>
    </div>
`)

	_buffer.WriteString(`
        </div>

    </div>
    <script src="/Static/js/jquery-3.3.1.min.js"></script>
    <script src="/Static/js/popper.min.js"></script>
    <script src="/Static/js/bootstrap.min.js"></script>
    <script src="/Static/js/bootstrap.bundle.min.js"></script>
    <script>
        $.get("/GetMenu",function (data) {
            $(".div-mainMenu").html(data)
        });
    </script>
    `)
	_buffer.WriteString(`
</body>

</html>`)
	w.Write(_buffer.Bytes())

}
