// Code generated by hero.
// source: E:\GOLANG\src\TopLearn\WebApp\template\Post.html
// DO NOT EDIT!
package gotemplate

import (
	"TopLearn/WebApp/datalayer"
	"TopLearn/WebApp/utility/time"
	"io"

	"github.com/shiyanhui/hero"
)

func PostHandler(post datalayer.Post, w io.Writer) {
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`<!DOCTYPE html>

<html lang="fa">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>بلاگ</title>
    <link rel="stylesheet" href="/Static/assets/dist/css/bootstrap.min.1.css" />
    <link rel="stylesheet" href="/Static/css/customCss.css" />
    `)
	_buffer.WriteString(`
</head>

<body>
    <div class="div-mainMenu"></div>
    <div class="container">

        <div class="row mt-4">
            `)
	_buffer.WriteString(`
    <div class="col-12 col-md-12 ">
        <div id="content">
            <div class="card mt-4 ">
                <div class="card-body text-primary">

                    <div class="row">
                        <div class="col-9">
                            <h4>`)
	hero.EscapeHTML(post.Title, _buffer)
	_buffer.WriteString(`</h4>
                        </div>
                        <div class="col-3">
                            <span>`)
	hero.EscapeHTML(time.ToPersian(post.CreateDate), _buffer)
	_buffer.WriteString(`</span>
                        </div>
                    </div>
                    <hr class="mt-0">
                    <img class="img-fluid img-thumbnail mx-auto d-block" src="/Images/Post/`)
	hero.EscapeHTML(post.Image, _buffer)
	_buffer.WriteString(`" alt="">
                    <br>
                    <div id="contentDiv">
                        <p class="text-medium text-justify">
                                `)
	hero.EscapeHTML(post.ShortDesc, _buffer)
	hero.EscapeHTML(post.LongDesc, _buffer)
	_buffer.WriteString(`  
                        </p>
                    </div>

                </div>
            </div>
        </div>
    </div>
`)

	_buffer.WriteString(`
        </div>

    </div>
    <script src="/Static/js/jquery-3.3.1.min.js"></script>
    <script src="/Static/js/popper.min.js"></script>
    <script src="/Static/js/bootstrap.min.js"></script>
    <script src="/Static/js/bootstrap.bundle.min.js"></script>
    <script>
        $.get("/GetMenu",function (data) {
            $(".div-mainMenu").html(data)
        });
    </script>
    `)
	_buffer.WriteString(`
</body>

</html>`)
	w.Write(_buffer.Bytes())

}
